name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

      # Step 3: Define IMAGE_TAG
      - name: Define IMAGE_TAG
        id: vars
        run: echo "IMAGE_TAG=$(date '+%d-%m-%Y_%H-%M')" >> $GITHUB_ENV

      # Step 4: Build the Docker image
      - name: Build Docker Image
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/raisehub_backend:${{ env.IMAGE_TAG }}


      # Step 5: Push the Docker image to Docker Hub
      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/raisehub_backend:${{ env.IMAGE_TAG }}

          # Step 6: Run the Docker container with secrets
      - name: Run the Docker container
        run: |
              docker run -d \
                    -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
                    -e MYSQL_USERNAME=${{ secrets.MYSQL_USERNAME }} \
                    -e MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }} \
                    -p 8080:8080 \
                    raisehub_backend:${{ env.IMAGE_TAG }}
