name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - uses: actions/checkout@v4

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Step 3: Define IMAGE_TAG
      - name: Define IMAGE_TAG
        id: vars
        run: echo "IMAGE_TAG=$(date +%s)" >> $GITHUB_ENV

      # Step 4: Display JWT_SECRET (for debugging purposes)
      - name: Echo JWT_SECRET
        run: echo "JWT_SECRET=${{ secrets.JWT_SECRET }} >> token.txt"  # Avoid this step in production if JWT_SECRET is sensitive

      - name: Cat JWT_SECRET
        run: cat token.txt

      # Step 5: Build the Docker image
      - name: Build the Docker image
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: docker build . --file Dockerfile --tag raisehub_backend:${{ env.IMAGE_TAG }}

      # Step 6: Tag the Docker image with the repository name.
      - name: Tag the Docker image
        run: docker tag raisehub_backend:${{ env.IMAGE_TAG }} ${{ secrets.DOCKER_USERNAME }}/raisehub_backend:${{ env.IMAGE_TAG }}

      # Step 7: Push the Docker image to Docker Hub
      - name: Push the Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/raisehub_backend:${{ env.IMAGE_TAG }}
