name: SonarQube

on:
  workflow_run:
    workflows: ["Java CI with Gradle"]  # Trigger this workflow after "Java CI with Gradle" completes
    types:
      - completed  # The workflow runs after the previous workflow has finished

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Cache SonarCloud Scanner
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar-scanner

      - name: Run SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v4
        with:
          args: >
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY}}
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION_KEY}}
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
            -Dsonar.sources=src
            -Dsonar.tests=test
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml