name: SonarQube analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pull-requests: read # allows SonarQube to decorate PRs with analysis results

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # Use the Adoptium Temurin distribution of OpenJDK
          java-version: '17'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Analyze with SonarQube
        uses: SonarSource/sonarqube-scan-action@7295e71c9583053f5bf40e9d4068a0c974603ec8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}     # SonarQube token stored in repo secrets
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}  # SonarQube host URL stored in repo secrets
        with:
          args: |
            -Dsonar.projectKey=<your-project-key>   # Replace with your SonarQube project key
            -Dsonar.sources=.                       # Path to your source code (default is current directory)
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}  # Using the SONAR_HOST_URL from secrets
