name: SonarQube analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pull-requests: read # allows SonarQube to decorate PRs with analysis results

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          check-latest: true

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Java Home
        # Ensures that JAVA_HOME is set correctly for the SonarQube scanner
        run: echo "JAVA_HOME_17_X64=$JAVA_HOME" >> $GITHUB_ENV

      - name: Analyze with SonarQube
        uses: SonarSource/sonarqube-scan-action@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}     # SonarQube token stored in repo secrets
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}  # SonarQube host URL stored in repo secrets
          JAVA_HOME: ${{ env.JAVA_HOME_17_X64 }}     # Ensuring SonarQube uses Java 17
        with:
          args: |
            -Dsonar.sources=.                       
