name: Run SonarQube with Gradle

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the code
      - uses: actions/checkout@v2

      # Step 2: Set up JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      # Step 3: Grant execute permissions to Gradle wrapper
      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      # Step 4: Run SonarQube Analysis with Gradle
      - name: Run SonarQube with Gradle
        run: ./gradlew build sonarqube \
          -Dsonar.projectKey=javareachabilityy \
          -Dsonar.organization=javareachabilityy \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        env:
          GIT_HUB_TOKEN: ${{ secrets.GIT_HUB_TOKEN }}
