name: SonarQube

on:
  workflow_run:
    workflows: ["Java CI with Gradle"]  # Trigger this workflow after "Java CI with Gradle" completes
    types:
      - completed  # The workflow runs after the previous workflow has finished

jobs:
  sonarqube:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: SonarQubeScan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}